### ISSUE TITLE
A1 - Bereitstellung des Content als Paket

### ISSUE THREAD

**Issue by eshadepunkt** [Dirkforthree/project04private#68]
# Beschreibung

Die Abspielsoftware und alle Inhalte müssen vor einer Konferenz als Paket bereitgestellt werden können, um eine einfache Installation auf dem Zielsystem zu ermöglichen. Das Paket muss alle notwendigen Komponenten und Dateien enthalten, um eine reibungslose Wiedergabe zu gewährleisten. Die Wiedergabe muss direkt nach der Installation starten können.

# Anmerkung

In wie fern hier tatsächlich ein echter Installer gebraucht wird, ist vom Team zu entscheiden. Wichtig ist jedoch, dass die Software solwohl beim Aufsetzen des Installation als auch bei der späteren Installation durch eine nicht technisch geprägte Person bedient werden kann.

# Task

- [x] Use cases überarbeiten
- [x] research packaging exe + data into one file
- [x] research open file ending windows
- [ ] Export to portable media
- [ ] Import from portable media
